; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MO"
#define MyAppVersion "5.0.0"
#define MyAppPublisher "INTERACTION LAB"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MO.exe"
#define MyAppAssocName MyAppName + "setup"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt


[Setup]
AppId={{E25905E1-CDF7-4E81-B10F-8560A967F489}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=Documents\{#MyAppName}
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
OutputDir=C:\MO-Autoupdater\temp\Output
OutputBaseFilename=MOsetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\ruta\a\curl.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MO-Autoupdater\temp\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\MO-Autoupdater\temp\tempbld\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[CustomMessages]
SelectPlugins=Select additional plugins to download and install:

[Code]
var
  PluginPage: TWizardPage;
  Plugin1CheckBox: TCheckBox;
  Plugin2CheckBox: TCheckBox;

procedure InitializeWizard;
begin
  // Crear una nueva página personalizada para la selección de plugins
  PluginPage := CreateCustomPage(wpSelectTasks, 'Select Plugins', CustomMessage('SelectPlugins'));

  // Crear checkboxes para cada plugin que el usuario puede seleccionar
  Plugin1CheckBox := TCheckBox.Create(PluginPage);
  Plugin1CheckBox.Parent := PluginPage.Surface;
  Plugin1CheckBox.Left := 10;
  Plugin1CheckBox.Top := 10;
  Plugin1CheckBox.Width := PluginPage.SurfaceWidth;
  Plugin1CheckBox.Caption := 'Plugin 1';

  Plugin2CheckBox := TCheckBox.Create(PluginPage);
  Plugin2CheckBox.Parent := PluginPage.Surface;
  Plugin2CheckBox.Left := 10;
  Plugin2CheckBox.Top := Plugin1CheckBox.Top + Plugin1CheckBox.Height + 5;
  Plugin2CheckBox.Width := PluginPage.SurfaceWidth;
  Plugin2CheckBox.Caption := 'Plugin 2';
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    // Verificar si el usuario seleccionó Plugin 1 para descargar
    if Plugin1CheckBox.Checked then
    begin
      MsgBox('Downloading Plugin 1...', mbInformation, MB_OK);
      if not Exec(ExpandConstant('{app}\curl.exe'), 'https://www.example.com/plugins/plugin1.zip -o "{app}\plugin1.zip"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        MsgBox('Failed to download Plugin 1. Please check your internet connection.', mbError, MB_OK);
      end;
    end;

    // Verificar si el usuario seleccionó Plugin 2 para descargar
    if Plugin2CheckBox.Checked then
    begin
      MsgBox('Downloading Plugin 2...', mbInformation, MB_OK);
      if not Exec(ExpandConstant('{app}\curl.exe'), 'https://www.example.com/plugins/plugin2.zip -o "{app}\plugin2.zip"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        MsgBox('Failed to download Plugin 2. Please check your internet connection.', mbError, MB_OK);
      end;
    end;
  end;
end;
